
function fillCategory()
{ 
 // this function is used to fill the category list on load
	//addOption(document.drop_list.country, "", "select", "");
	addOption(document.drop_list.country, "101", "INDIA", "");
	addOption(document.drop_list.country, "1","Afghanistan","");
	addOption(document.drop_list.country, "2","Aringland Islands","");
	addOption(document.drop_list.country, "3","Albania","");
	addOption(document.drop_list.country, "4","Algeria","");
	addOption(document.drop_list.country, "5","American Samoa","");
	addOption(document.drop_list.country, "6","Andorra","");
	addOption(document.drop_list.country, "7","Angola","");
	addOption(document.drop_list.country, "8","Anguilla","");
	addOption(document.drop_list.country, "9","Antarctica","");
	addOption(document.drop_list.country, "10","Antigua and Barbuda","");
	addOption(document.drop_list.country, "11","Argentina","");
	addOption(document.drop_list.country, "12","Armenia","");
	addOption(document.drop_list.country, "13","Aruba","");
	addOption(document.drop_list.country, "14","Australia","");
	addOption(document.drop_list.country, "15","Austria","");
	addOption(document.drop_list.country, "16","Azerbaijan","");
	addOption(document.drop_list.country, "17","Bahamas","");
	addOption(document.drop_list.country, "18","Bahrain","");
	addOption(document.drop_list.country, "19","Bangladesh","");
	addOption(document.drop_list.country, "20","Barbados","");
	addOption(document.drop_list.country, "21","Belarus","");
	addOption(document.drop_list.country, "22","Belgium","");
	addOption(document.drop_list.country, "23","Belize","");
	addOption(document.drop_list.country, "24","Benin","");
	addOption(document.drop_list.country, "25","Bermuda","");
	addOption(document.drop_list.country, "26","Bhutan","");
	addOption(document.drop_list.country, "27","Bolivia","");
	addOption(document.drop_list.country, "28","Bosnia and Herzegovina","");
	addOption(document.drop_list.country, "29","Botswana","");
	addOption(document.drop_list.country, "30","Bouvet Island","");
	addOption(document.drop_list.country, "31","Brazil","");
	addOption(document.drop_list.country, "32","British Indian Ocean territory","");
	addOption(document.drop_list.country, "33","Brunei Darussalam","");
	addOption(document.drop_list.country, "34","Bulgaria","");
	addOption(document.drop_list.country, "35","Burkina Faso","");
	addOption(document.drop_list.country, "36","Burundi","");
	addOption(document.drop_list.country, "37","Cambodia","");
	addOption(document.drop_list.country, "38","Cameroon","");
	addOption(document.drop_list.country, "39","Canada","");
	addOption(document.drop_list.country, "40","Cape Verde","");
	addOption(document.drop_list.country, "41","Cayman Islands","");
	addOption(document.drop_list.country, "42","Central African Republic","");
	addOption(document.drop_list.country, "43","Chad","");
	addOption(document.drop_list.country, "44","Chile","");
	addOption(document.drop_list.country, "45","China","");
	addOption(document.drop_list.country, "46","Christmas Island","");
	addOption(document.drop_list.country, "47","Cocos (Keeling) Islands","");
	addOption(document.drop_list.country, "48","Colombia","");
	addOption(document.drop_list.country, "49","Comoros","");
	addOption(document.drop_list.country, "50","Congo","");
	addOption(document.drop_list.country, "51","Congo","");
	addOption(document.drop_list.country, "52"," Democratic Republic","");
	addOption(document.drop_list.country, "53","Cook Islands","");
	addOption(document.drop_list.country, "54","Costa Rica","");
	addOption(document.drop_list.country, "55","Ivory Coast (Ivory Coast)","");
	addOption(document.drop_list.country, "56","Croatia (Hrvatska)","");
	addOption(document.drop_list.country, "57","Cuba","");
	addOption(document.drop_list.country, "58","Cyprus","");
	addOption(document.drop_list.country, "59","Czech Republic","");
	addOption(document.drop_list.country, "60","Denmark","");
	addOption(document.drop_list.country, "61","Djibouti","");
	addOption(document.drop_list.country, "62","Dominica","");
	addOption(document.drop_list.country, "63","Dominican Republic","");
	addOption(document.drop_list.country, "64","East Timor","");
	addOption(document.drop_list.country, "65","Ecuador","");
	addOption(document.drop_list.country, "66","Egypt","");
	addOption(document.drop_list.country, "67","El Salvador","");
	addOption(document.drop_list.country, "68","Equatorial Guinea","");
	addOption(document.drop_list.country, "69","Eritrea","");
	addOption(document.drop_list.country, "70","Estonia","");
	addOption(document.drop_list.country, "71","Ethiopia","");
	addOption(document.drop_list.country, "72","Falkland Islands","");
	addOption(document.drop_list.country, "73","Faroe Islands","");
	addOption(document.drop_list.country, "74","Fiji","");
	addOption(document.drop_list.country, "75","Finland","");
	addOption(document.drop_list.country, "76","France","");
	addOption(document.drop_list.country, "77","French Guiana","");
	addOption(document.drop_list.country, "78","French Polynesia","");
	addOption(document.drop_list.country, "79","French Southern Territories","");
	addOption(document.drop_list.country, "80","Gabon","");
	addOption(document.drop_list.country, "81","Gambia","");
	addOption(document.drop_list.country, "82","Georgia","");
	addOption(document.drop_list.country, "83","Germany","");
	addOption(document.drop_list.country, "84","Ghana","");
	addOption(document.drop_list.country, "85","Gibraltar","");
	addOption(document.drop_list.country, "86","Greece","");
	addOption(document.drop_list.country, "87","Greenland","");
	addOption(document.drop_list.country, "88","Grenada","");
	addOption(document.drop_list.country, "89","Guadeloupe","");
	addOption(document.drop_list.country, "90","Guam","");
	addOption(document.drop_list.country, "91","Guatemala","");
	addOption(document.drop_list.country, "92","Guinea","");
	addOption(document.drop_list.country, "93","Guinea-Bissau","");
	addOption(document.drop_list.country, "94","Guyana","");
	addOption(document.drop_list.country, "95","Haiti","");
	addOption(document.drop_list.country, "96","Heard and McDonald Islands","");
	addOption(document.drop_list.country, "97","Honduras","");
	addOption(document.drop_list.country, "98","Hong Kong","");
	addOption(document.drop_list.country, "99","Hungary","");
	addOption(document.drop_list.country, "100","Iceland","");
	//addOption(document.drop_list.country, "101","India","");
	addOption(document.drop_list.country, "102","Indonesia","");
	addOption(document.drop_list.country, "103","Iran","");
	addOption(document.drop_list.country, "104","Iraq","");
	addOption(document.drop_list.country, "105","Ireland","");
	addOption(document.drop_list.country, "106","Israel","");
	addOption(document.drop_list.country, "107","Italy","");
	addOption(document.drop_list.country, "108","Jamaica","");
	addOption(document.drop_list.country, "109","Japan","");
	addOption(document.drop_list.country, "110","Jordan","");
	addOption(document.drop_list.country, "111","Kazakhstan","");
	addOption(document.drop_list.country, "112","Kenya","");
	addOption(document.drop_list.country, "113","Kiribati","");
	addOption(document.drop_list.country, "114","Korea (north)","");
	addOption(document.drop_list.country, "115","Korea (south)","");
	addOption(document.drop_list.country, "116","Kuwait","");
	addOption(document.drop_list.country, "117","Kyrgyzstan","");
	addOption(document.drop_list.country, "118","Lao People's Democratic Republic","");
	addOption(document.drop_list.country, "119","Latvia","");
	addOption(document.drop_list.country, "120","Lebanon","");
	addOption(document.drop_list.country, "121","Lesotho","");
	addOption(document.drop_list.country, "122","Liberia","");
	addOption(document.drop_list.country, "123","Libyan Arab Jamahiriya","");
	addOption(document.drop_list.country, "124","Liechtenstein","");
	addOption(document.drop_list.country, "125","Lithuania","");
	addOption(document.drop_list.country, "126","Luxembourg","");
	addOption(document.drop_list.country, "127","Macao","");
	addOption(document.drop_list.country, "128","Macedonia","");
	addOption(document.drop_list.country, "129","Madagascar","");
	addOption(document.drop_list.country, "130","Malawi","");
	addOption(document.drop_list.country, "131","Malaysia","");
	addOption(document.drop_list.country, "132","Maldives","");
	addOption(document.drop_list.country, "133","Mali","");
	addOption(document.drop_list.country, "134","Malta","");
	addOption(document.drop_list.country, "135","Marshall Islands","");
	addOption(document.drop_list.country, "136","Martinique","");
	addOption(document.drop_list.country, "137","Mauritania","");
	addOption(document.drop_list.country, "138","Mauritius","");
	addOption(document.drop_list.country, "139","Mayotte","");
	addOption(document.drop_list.country, "140","Mexico","");
	addOption(document.drop_list.country, "141","Micronesia","");
	addOption(document.drop_list.country, "142","Moldova","");
	addOption(document.drop_list.country, "143","Monaco","");
	addOption(document.drop_list.country, "144","Mongolia","");
	addOption(document.drop_list.country, "145","Montserrat","");
	addOption(document.drop_list.country, "146","Morocco","");
	addOption(document.drop_list.country, "147","Mozambique","");
	addOption(document.drop_list.country, "148","Myanmar","");
	addOption(document.drop_list.country, "149","Namibia","");
	addOption(document.drop_list.country, "150","Nauru","");
	addOption(document.drop_list.country, "151","Nepal","");
	addOption(document.drop_list.country, "152","Netherlands","");
	addOption(document.drop_list.country, "153","Netherlands Antilles","");
	addOption(document.drop_list.country, "154","New Caledonia","");
	addOption(document.drop_list.country, "155","New Zealand","");
	addOption(document.drop_list.country, "156","Nicaragua","");
	addOption(document.drop_list.country, "157","Niger","");
	addOption(document.drop_list.country, "158","Nigeria","");
	addOption(document.drop_list.country, "159","Niue","");
	addOption(document.drop_list.country, "160","Norfolk Island","");
	addOption(document.drop_list.country, "161","Northern Mariana Islands","");
	addOption(document.drop_list.country, "162","Norway","");
	addOption(document.drop_list.country, "163","Oman","");
	addOption(document.drop_list.country, "164","Pakistan","");
	addOption(document.drop_list.country, "165","Palau","");
	addOption(document.drop_list.country, "166","Palestinian Territories","");
	addOption(document.drop_list.country, "167","Panama","");
	addOption(document.drop_list.country, "168","Papua New Guinea","");
	addOption(document.drop_list.country, "169","Paraguay","");
	addOption(document.drop_list.country, "170","Peru","");
	addOption(document.drop_list.country, "171","Philippines","");
	addOption(document.drop_list.country, "172","Pitcairn","");
	addOption(document.drop_list.country, "173","Poland","");
	addOption(document.drop_list.country, "174","Portugal","");
	addOption(document.drop_list.country, "175","Puerto Rico","");
	addOption(document.drop_list.country, "176","Qatar","");
	addOption(document.drop_list.country, "177","Runion","");
	addOption(document.drop_list.country, "178","Romania","");
	addOption(document.drop_list.country, "179","Russian Federation","");
	addOption(document.drop_list.country, "180","Rwanda","");
	addOption(document.drop_list.country, "181","Saint Helena","");
	addOption(document.drop_list.country, "182","Saint Kitts and Nevis","");
	addOption(document.drop_list.country, "183","Saint Lucia","");
	addOption(document.drop_list.country, "184","Saint Pierre and Miquelon","");
	addOption(document.drop_list.country, "185","Saint Vincent and the Grenadines","");
	addOption(document.drop_list.country, "186","Samoa","");
	addOption(document.drop_list.country, "187","San Marino","");
	addOption(document.drop_list.country, "188","Sao Tome and Principe","");
	addOption(document.drop_list.country, "189","Saudi Arabia","");
	addOption(document.drop_list.country, "190","Senegal","");
	addOption(document.drop_list.country, "191","Serbia and Montenegro","");
	addOption(document.drop_list.country, "192","Seychelles","");
	addOption(document.drop_list.country, "193","Sierra Leone","");
	addOption(document.drop_list.country, "194","Singapore","");
	addOption(document.drop_list.country, "195","Slovakia","");
	addOption(document.drop_list.country, "196","Slovenia","");
	addOption(document.drop_list.country, "197","Solomon Islands","");
	addOption(document.drop_list.country, "198","Somalia","");
	addOption(document.drop_list.country, "199","South Africa","");
	addOption(document.drop_list.country, "200","South Georgia and the South Sandwich Islands","");
	addOption(document.drop_list.country, "201","Spain","");
	addOption(document.drop_list.country, "202","Sri Lanka","");
	addOption(document.drop_list.country, "203","Sudan","");
	addOption(document.drop_list.country, "204","Suriname","");
	addOption(document.drop_list.country, "205","Svalbard and Jan Mayen Islands","");
	addOption(document.drop_list.country, "206","Swaziland","");
	addOption(document.drop_list.country, "207","Sweden","");
	addOption(document.drop_list.country, "208","Switzerland","");
	addOption(document.drop_list.country, "209","Syria","");
	addOption(document.drop_list.country, "210","Taiwan","");
	addOption(document.drop_list.country, "211","Tajikistan","");
	addOption(document.drop_list.country, "212","Tanzania","");
	addOption(document.drop_list.country, "213","Thailand","");
	addOption(document.drop_list.country, "214","Togo","");
	addOption(document.drop_list.country, "215","Tokelau","");
	addOption(document.drop_list.country, "216","Tonga","");
	addOption(document.drop_list.country, "217","Trinidad and Tobago","");
	addOption(document.drop_list.country, "218","Tunisia","");
	addOption(document.drop_list.country, "219","Turkey","");
	addOption(document.drop_list.country, "220","Turkmenistan","");
	addOption(document.drop_list.country, "221","Turks and Caicos Islands","");
	addOption(document.drop_list.country, "222","Tuvalu","");
	addOption(document.drop_list.country, "223","Uganda","");
	addOption(document.drop_list.country, "224","Ukraine","");
	addOption(document.drop_list.country, "225","United Arab Emirates","");
	addOption(document.drop_list.country, "226","United Kingdom","");
	addOption(document.drop_list.country, "227","United States of America","");
	addOption(document.drop_list.country, "228","Uruguay","");
	addOption(document.drop_list.country, "229","Uzbekistan","");
	addOption(document.drop_list.country, "230","Vanuatu","");
	addOption(document.drop_list.country, "231","Vatican City","");
	addOption(document.drop_list.country, "232","Venezuela","");
	addOption(document.drop_list.country, "233","Vietnam","");
	addOption(document.drop_list.country, "234","Virgin Islands (British)","");
	addOption(document.drop_list.country, "235","Virgin Islands (US)","");
	addOption(document.drop_list.country, "236","Wallis and Futuna Islands","");
	addOption(document.drop_list.country, "237","Western Sahara","");
	addOption(document.drop_list.country, "238","Yemen","");
	addOption(document.drop_list.country, "239","Zaire","");
	addOption(document.drop_list.country, "240","Zambia","");
	addOption(document.drop_list.country, "241","Zimbabwe","");
	

	d3=document.getElementById('location1');
	d3.style.visibility="hidden";
	d1=document.getElementById('error');
	d1.style.visibility="hidden";
//selectlocation();
}

function Selectlocation()
{
	// ON selection of category this function will work
	removeAllOptions(document.drop_list.location);
	//addOption(document.drop_list.location, "", "select", "");
	if(document.drop_list.country.value == '101')
	{
		addOption(document.drop_list.location,"", "select","");
		addOption(document.drop_list.location,"1", "Ahmedabad", "");
		addOption(document.drop_list.location,"2","Bangalore","");
		addOption(document.drop_list.location,"3","Chennai","");
		addOption(document.drop_list.location,"4","Delhi","");
		addOption(document.drop_list.location,"5","Gurgaon","");
		addOption(document.drop_list.location,"6","Hyderabad","");
		addOption(document.drop_list.location,"7","Kolkata","");
		addOption(document.drop_list.location,"8","Mumbai","");
		addOption(document.drop_list.location,"9","Noida","");
		addOption(document.drop_list.location,"10","Pune","");
		addOption(document.drop_list.location,"11","Agartala","");
		addOption(document.drop_list.location,"12","Agra","");
		addOption(document.drop_list.location,"13","Ahmednagar","");
		addOption(document.drop_list.location,"14","Aizawal","");
		addOption(document.drop_list.location,"15","Ajmer","");
		addOption(document.drop_list.location,"16","Aligarh","");
		addOption(document.drop_list.location,"17","Allahabad","");
		addOption(document.drop_list.location,"18","Ambala","");
		addOption(document.drop_list.location,"19","Amritsar","");
		addOption(document.drop_list.location,"20","Anand","");
		addOption(document.drop_list.location,"21","Ankleshwar","");
		addOption(document.drop_list.location,"22","Asansol","");
		addOption(document.drop_list.location,"23","Aurangabad","");
		addOption(document.drop_list.location,"24","Bahgalpur","");
		addOption(document.drop_list.location,"25","Bareilly","");
		addOption(document.drop_list.location,"26","Baroda","");
		addOption(document.drop_list.location,"27","Belgaum","");
		addOption(document.drop_list.location,"28","Bellary","");
		addOption(document.drop_list.location,"29","Bharuch","");
		addOption(document.drop_list.location,"30","Bhatinda","");
		addOption(document.drop_list.location,"31","Bhavanagar","");
		addOption(document.drop_list.location,"32","Bharathidasan","");
		addOption(document.drop_list.location,"33","Bhilaigarh","");
		addOption(document.drop_list.location,"34","Bhopal","");
		addOption(document.drop_list.location,"35","Bhubaneswar","");
		addOption(document.drop_list.location,"36","Bhuj","");
		addOption(document.drop_list.location,"37","Bidar","");
		addOption(document.drop_list.location,"38","Billaspur","");
		addOption(document.drop_list.location,"39","Bokaro","");
		addOption(document.drop_list.location,"40","Calicut","");
		addOption(document.drop_list.location,"41","Chandigarh","");
		addOption(document.drop_list.location,"42","Coimbatore","");
		addOption(document.drop_list.location,"43","Cuttack","");
		addOption(document.drop_list.location,"44","Delhousie","");
		addOption(document.drop_list.location,"45","Dhaman","");
		addOption(document.drop_list.location,"46","Dehradun","");
		addOption(document.drop_list.location,"47","Dhanbad","");
		addOption(document.drop_list.location,"48","Dharmasala","");
		addOption(document.drop_list.location,"49","Dharwad","");
		addOption(document.drop_list.location,"50","Dispur","");
		addOption(document.drop_list.location,"51","Durga pur","");
		addOption(document.drop_list.location,"52","Ernakulam","");
		addOption(document.drop_list.location,"53","Erode","");
		addOption(document.drop_list.location,"54","Faizabad","");
		addOption(document.drop_list.location,"55","Faridabad","");
		addOption(document.drop_list.location,"56","Gandhinagar","");
		addOption(document.drop_list.location,"57","Gangtok","");
		addOption(document.drop_list.location,"58","Ghaziabad","");
		addOption(document.drop_list.location,"59","Goa","");
		addOption(document.drop_list.location,"60","Gorakhpur","");
		addOption(document.drop_list.location,"61","Gulbarga","");
		addOption(document.drop_list.location,"62","Guntur","");
		addOption(document.drop_list.location,"63","Guwahati","");
		addOption(document.drop_list.location,"64","Gwalior","");
		addOption(document.drop_list.location,"65","Hamirpur","");
		addOption(document.drop_list.location,"66","Haldia","");
		addOption(document.drop_list.location,"67","Hisar","");
		addOption(document.drop_list.location,"68","Hosur","");
		addOption(document.drop_list.location,"69","Hubli","");
		addOption(document.drop_list.location,"70","Impal","");
		addOption(document.drop_list.location,"71","Indore","");
		addOption(document.drop_list.location,"72","Itanagar","");
		addOption(document.drop_list.location,"73","Jabalpur","");
		addOption(document.drop_list.location,"74","Jaipur","");
		addOption(document.drop_list.location,"75","Jaiselmer","");
		addOption(document.drop_list.location,"76","Jalander","");
		addOption(document.drop_list.location,"77","Jalgaion","");
		addOption(document.drop_list.location,"78","Jammu","");
		addOption(document.drop_list.location,"79","Jamnagar","");
		addOption(document.drop_list.location,"80","Jamshadpur","");
		addOption(document.drop_list.location,"81","Jodhpur","");
		addOption(document.drop_list.location,"82","Kakinada","");
		addOption(document.drop_list.location,"83","Kandla","");
		addOption(document.drop_list.location,"84","Kannur","");
		addOption(document.drop_list.location,"85","Kanpur","");
		addOption(document.drop_list.location,"86","Karnal","");
		addOption(document.drop_list.location,"87","Kavarathi","");
		addOption(document.drop_list.location,"88","Khargpur","");
		addOption(document.drop_list.location,"89","Kochi","");
		addOption(document.drop_list.location,"90","Kohima","");
		addOption(document.drop_list.location,"91","Kolar","");
		addOption(document.drop_list.location,"92","Kolhapur","");
		addOption(document.drop_list.location,"93","Kolam","");
		addOption(document.drop_list.location,"94","Kota","");
		addOption(document.drop_list.location,"95","Kottayam","");
		addOption(document.drop_list.location,"96","Kulu manali","");
		addOption(document.drop_list.location,"97","Kurnool","");
		addOption(document.drop_list.location,"98","Kurukshetra","");
		addOption(document.drop_list.location,"99","Lucknow","");
		addOption(document.drop_list.location,"100","Ludhiana","");
		addOption(document.drop_list.location,"101","Madurai","");
		addOption(document.drop_list.location,"102","Mangalore","");
		addOption(document.drop_list.location,"103","Mathura","");
		addOption(document.drop_list.location,"104","Meerut","");
		addOption(document.drop_list.location,"105","Mohali","");
		addOption(document.drop_list.location,"106","Moradabad","");
		addOption(document.drop_list.location,"107","Mysore","");
		addOption(document.drop_list.location,"108","Nagercoil","");
		addOption(document.drop_list.location,"109","Nagpur","");
		addOption(document.drop_list.location,"110","Nasik","");
		addOption(document.drop_list.location,"111","Nellore","");
		addOption(document.drop_list.location,"112","Nizamabad","");
		addOption(document.drop_list.location,"113","Ooty","");
		addOption(document.drop_list.location,"114","Pallakool","");
		addOption(document.drop_list.location,"115","Panipat","");
		addOption(document.drop_list.location,"116","Paradeep","");
		addOption(document.drop_list.location,"117","Pathonkot","");
		addOption(document.drop_list.location,"118","Patiala","");
		addOption(document.drop_list.location,"119","Patna","");
		addOption(document.drop_list.location,"120","Pondicherry","");
		addOption(document.drop_list.location,"121","Porbandhar","");
		addOption(document.drop_list.location,"122","Port blair","");
		addOption(document.drop_list.location,"123","Puri","");
		addOption(document.drop_list.location,"124","Quilion","");
		addOption(document.drop_list.location,"125","Raipur","");
		addOption(document.drop_list.location,"126","Rajahmundry","");
		addOption(document.drop_list.location,"127","Rajkot","");
		addOption(document.drop_list.location,"128","Ranchi","");
		addOption(document.drop_list.location,"129","Rohtak","");
		addOption(document.drop_list.location,"130","Roorkee","");
		addOption(document.drop_list.location,"131","Salem","");
		addOption(document.drop_list.location,"132","Shilling","");
		addOption(document.drop_list.location,"133","Shimla","");
		addOption(document.drop_list.location,"134","Sholapur","");
		addOption(document.drop_list.location,"135","Silchar","");
		addOption(document.drop_list.location,"136","Siliguri","");
		addOption(document.drop_list.location,"137","Silvassa","");
		addOption(document.drop_list.location,"138","Srinagar","");
		addOption(document.drop_list.location,"139","Surat","");
		addOption(document.drop_list.location,"140","Suratkal","");
		addOption(document.drop_list.location,"141","Tanzavur","");
		addOption(document.drop_list.location,"142","Thrissur","");
		addOption(document.drop_list.location,"143","Tirunalveli","");
		addOption(document.drop_list.location,"144","Tirupathi","");
		addOption(document.drop_list.location,"145","Tiruvanthapuram","");
		addOption(document.drop_list.location,"146","Trichy","");
		addOption(document.drop_list.location,"147","Tuticorin","");
		addOption(document.drop_list.location,"148","Udaipur","");
		addOption(document.drop_list.location,"149","Ujjain","");
		addOption(document.drop_list.location,"150","Vadodara","");
		addOption(document.drop_list.location,"151","Valsad","");
		addOption(document.drop_list.location,"152","Vapi","");
		addOption(document.drop_list.location,"153","Varanasi","");
		addOption(document.drop_list.location,"154","Vellore","");
		addOption(document.drop_list.location,"155","Vijayawada","");
		addOption(document.drop_list.location,"156","Visakhapatnam","");
		addOption(document.drop_list.location,"157","Warangal","");
			
		d3=document.getElementById('location1');
		d3.style.visibility="hidden";
		d1=document.getElementById('error');
		d1.style.visibility="hidden";
	}
	if(document.drop_list.country.value != 101)
	{
		addOption(document.drop_list.location,"other", "other","");
		d3.style.visibility="visible";
		d1.style.visibility="visible";
	}
}

function removeAllOptions(selectbox)
{
	var i;
	for(i=selectbox.options.length-1;i>=0;i--)
	{
		//selectbox.options.remove(i);
		selectbox.remove(i);
	}
}
function addOption(selectbox, value, text )
{
	var optn = document.createElement("OPTION");
	optn.text = text;
	optn.value = value;
 
	selectbox.options.add(optn);
}
