<tr>
    <td align="center"><!--<div align="center" class="style3"><a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=index&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Home</a> | <a href="http://affiliate.travelnow.com/affiliates/home.jsp?ref=tvn">Become an Affiliate</a> | <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=viewOrCancelReservation&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">View/Cancel Reservation</a> &nbsp;| <a href="http://dg.travelnow.com/index.jsp?cid=1">Destination Guides</a>&nbsp;|&nbsp; <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=hotelSpecials&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Hotel Deals</a>&nbsp;| <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=groups&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Groups</a>&nbsp;| <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=faq&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Help/FAQ</a>&nbsp;| <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=newsletters&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Newsletters</a>&nbsp;| <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=contactUs&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Contact Us</a>&nbsp;| <a href="http://travel.ian.com/index.jsp;jsessionid=580F53446BDA10359C296BDC166C477C.tn03tc01?pageName=advertising&amp;currencyCode=USD&amp;additionalDataString=vrBookingSource%7Cindex&amp;locale=en_US&amp;cid=1">Advertise with Us</a> </div>-->
      <div></div>
      <div align="center" class="style3"> <?=WEBSITE_NAME?> is not responsible for content on external web sites. <br />
        <br />
        Copyright &copy; 2010 <?=WEBSITE_NAME?>, LP. All rights reserved.&nbsp;&nbsp; </div>
      <div></div>
      <div></div>
       
      <div></div>
      <!--<div align="center" class="style3"> Partners:&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.citysearch.com">Citysearch</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.expedia.com">Expedia</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.evite.com">Evite</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.hsn.com" target="_blank">HSN</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.ticketmaster.com" target="_blank">Ticketmaster</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.reserveamerica.com" target="_blank">ReserveAmerica</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.hotwire.com" target="_blank">Hotwire</a><br />
        <a href="http://www.lendingtree.com/stm/default.asp" target="_blank">LendingTree</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.realestate.com" target="_blank">RealEstate.com</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.gifts.com" target="_blank">Gifts.com</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.entertainment.com" target="_blank">Entertainment.com</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.match.com" target="_blank">Match.com</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.tripadvisor.com" target="_blank">TripAdvisor</a><br />
    <a href="http://www.condosaver.com" target="_blank">CondoSaver.com</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.classicvacations.com" target="_blank">ClassicVacations.com</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.livedaily.com" target="_blank">liveDaily</a> &nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.vacationspot.com" target="_blank">VacationSpot.com</a></div>--></td>
  </tr>