XML:
<?xml version='1.0' encoding='utf-8'?>
<ARBCreateSubscriptionRequest xmlns='AnetApi/xml/v1/schema/AnetApiSchema.xsd'>
  <merchantAuthentication>
    <name>733N7TvPF2zx</name>
    <transactionKey>6bAy8253FK2fR55b</transactionKey>
  </merchantAuthentication>
  <refId></refId>
  <subscription>
    <name></name>
    <paymentSchedule>
      <interval>
        <length>1</length>
        <unit>months</unit>
      </interval>
      <startDate>2011-03-16</startDate>
      <totalOccurrences>9999</totalOccurrences>
      <trialOccurrences>0</trialOccurrences>
    </paymentSchedule>
    <amount>29.99</amount>
    <trialAmount>0</trialAmount>
    <payment>
      <creditCard>
        <cardNumber>370000000000002</cardNumber>
        <expirationDate>2016-16</expirationDate>
      </creditCard>
    </payment>
    <order>
      <invoiceNumber></invoiceNumber>
      <description></description>
    </order>
    <customer>
      <id></id>
      <email></email>
      <phoneNumber></phoneNumber>
      <faxNumber></faxNumber>
    </customer>
    <billTo>
      <firstName>John</firstName>
      <lastName>Conde</lastName>
      <company></company>
      <address>
      123 Main Street
      </address>
      <city>Townsville</city>
      <state>NJ</state>
      <zip>12345</zip>
    </billTo>
    <shipTo>
      <firstName></firstName>
      <lastName></lastName>
      <company></company>
      <address>
      </address>
      <city></city>
      <state></state>
      <zip></zip>
    </shipTo>
  </subscription>
</ARBCreateSubscriptionRequest>
